const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    getSettings: () => ipcRenderer.invoke('get-settings'),
    setSetting: (key, value) => ipcRenderer.invoke('set-setting', key, value),
    getIpaDict: () => ipcRenderer.invoke('get-ipa-dict'),
    getBanglaDict: () => ipcRenderer.invoke('get-bangla-dict'),
    getPracticeLessons: () => ipcRenderer.invoke('get-practice-lessons'),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    installAppUpdate: () => ipcRenderer.invoke('install-app-update'),
    checkAppUpdate: () => ipcRenderer.invoke('check-app-update'),
    hideWindow: () => ipcRenderer.invoke('app-hide'),
    quitApp: () => ipcRenderer.invoke('app-quit'),
    setZoom: (dir) => ipcRenderer.invoke('app-zoom', dir),
    toggleFullScreen: () => ipcRenderer.invoke('app-fullscreen'),
    onClipboardUpdate: (callback) => ipcRenderer.on('clipboard-update', (_event, value) => callback(value)),
    onClearHistory: (callback) => ipcRenderer.on('clear-history', (_event) => callback()),
    onClearEntry: (callback) => ipcRenderer.on('clear-entry', (_event) => callback()),
    onCopyIpa: (callback) => ipcRenderer.on('copy-ipa', (_event) => callback()),
    onCopyBangla: (callback) => ipcRenderer.on('copy-bangla', (_event) => callback()),
    onShowSettings: (callback) => ipcRenderer.on('show-settings', (_event) => callback()),
    onShowAbout: (callback) => ipcRenderer.on('show-about', (_event) => callback()),
    onDictsUpdated: (callback) => ipcRenderer.on('dicts-updated', (_event, value) => callback(value)),
    onMaterialsUpdated: (callback) => ipcRenderer.on('materials-updated', (_event, value) => callback(value)),
    onAppUpdate: (callback) => ipcRenderer.on('app-update', (_event, value) => callback(value)),
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    openPractice: () => ipcRenderer.invoke('open-practice'),
    startPracticeSpeech: (payload) => ipcRenderer.invoke('start-practice-speech', payload),
    stopPracticeSpeech: () => ipcRenderer.invoke('stop-practice-speech'),
    onPracticeSpeech: (callback) => ipcRenderer.on('practice-speech', (_event, value) => callback(value)),
    getOrtWasmDir: () => ipcRenderer.invoke('get-ort-wasm-dir')
});
